name: server

on:

    push:
        branches:
            - main
    pull_request:
            branches:
                - main

jobs:

    server:

        runs-on: ubuntu-latest

        services:
            redis:
                image: redis:alpine
                ports:
                    - 6379:6379

        steps:

            - uses: actions/checkout@v3

            - uses: actions/setup-python@v5
              with:
                python-version: 3.14

            
            - name: get dependences
              run: pip install -r requirements.txt

            - name: init server
              run: |
               python -m tests.functional.cli server run tests.functional.api:app --detached
               sleep 10

            
            - name: execute client
              run: python -m tests.functional.client

            - name: get logs
              run: python -m tests.functional.cli server logs --token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmdW5jdGlvbmFsLWNsaS10ZXN0IiwidHlwZSI6InVzZXJfdG9rZW4iLCJleHAiOjE3OTE2NzIxOTF9.8I2j-eTTR3ZFbll7BRzSa-ou2eT15P0c38EdZhv7rgM
            
            